# -*- coding: utf-8 -*-

require 'yaml'
require 'rake/clean'

CONFIG_FILE = "config.yml"

CONFIG = YAML.load(File.open(CONFIG_FILE))
BOOKNAME = CONFIG["bookname"]
EPUB_FILE = "#{BOOKNAME}.epub"
RE_CHAPS = File.read("CHAPS").split rescue []
RE_PREDEF = File.read("PREDEF").split rescue []
RE_POSTDEF = File.read("POSTDEF").split rescue []
RE_FILES = RE_PREDEF + RE_CHAPS + RE_POSTDEF

CLOBBER.include(EPUB_FILE)
CLEAN.include(BOOKNAME + "-epub")

task :default => [EPUB_FILE]

desc "EPUBファイルを生成"
file EPUB_FILE => RE_FILES do
  sh "rm -f #{EPUB_FILE}"
  sh "rm -rf #{BOOKNAME + "-epub"}"
  sh "review-epubmaker #{CONFIG_FILE}"
end
